apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: gitops-foundations
  namespace: argo-demo
  labels:
    app: gitops-foundations
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: app.gitops-foundations-demo.westus2.cloudapp.azure.com
      http:
        paths:
          - backend:
              serviceName: gitops-foundations-load-balancer
              servicePort: 80
